version: '3.1'
services:
  db:
    image:
      postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 452814
      POSTGRES_DB: ads
  web:
    build: .
    ports:
      - 5555:9999
    links:
      - db
