version: '3.1'
services:
  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 9999:9999
  db:
    image:
      postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 452814
      POSTGRES_DB: ads
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
